### ISSUE TITLE
Error when trying to run now-compose on existing docker-compose.yml

### ISSUE THREAD

**Issue by vincentwongso** [dannav/now-compose#6]
I've got TypeError error when trying to run on existing docker-compose.yml file:
```
now-compose -f docker-compose.yml up -d
```

The error message:
```
ERROR: TypeError: Path must be a string. Received { context: '.', dockerfile: '.docker/php/Dockerfile' }
```

My docker-compose.yml file:
```
version: "3"
networks:
  app-tier:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    networks:
      - app-tier
    ports:
      - 9002:9000
    volumes:
      - .:/srv/app
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    networks:
      - app-tier
    ports:
      - 8080:80
    volumes:
      - ./public:/srv/app/public
```

**Comment by dannav** [comment]
So currently only the path to the Dockerfile to build is supported. You've defined an object with `context` and `dockerfile` props.

Try this and let me know if that solves any issues:

```
version: "3"
networks:
  app-tier:
    driver: bridge
services:
  app:
    build: ./.docker/php/Dockerfile
    networks:
      - app-tier
    ports:
      - 9002:9000
    volumes:
      - .:/srv/app
  nginx:
    build: ./.docker/nginx/Dockerfile
    networks:
      - app-tier
    ports:
      - 8080:80
    volumes:
      - ./public:/srv/app/public
```
